import type {Metadata} from "next";
import {Inter} from "next/font/google";
import Footer from "@/components/layout/footer";
import Navbar from "@/components/layout/navbar";
import {Providers} from "./providers";

import "./globals.css";

const inter = Inter({subsets: ['latin']});

export const metadata: Metadata = {
    title: "AllCritics",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={inter.className}
        >
        <Providers>
            <Navbar/>
            {children}
            <Footer/>
        </Providers>

        </body>
        </html>
    );
}
